# Generated by Django 4.1.3 on 2023-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('prizing', models.CharField(max_length=255)),
                ('classs', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
