# Generated by Django 4.1.3 on 2023-09-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_bookingdetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
